### ISSUE TITLE
Call to a member function getClassHandle() on null

### ISSUE THREAD

**Issue by edolyne** [fruitstudios/LinkIt#67]
Current Install:

CraftCMS version: 2.6.2968
LinkIt version: 2.3.4

With this installed, and attempting to create or edit entries that use a LinkIt field type I am getting a internal server error of: `Call to a member function getClassHandle() on null`

The runtime logs show:
```
#17 /storage/av04327/www/craft/plugins/fruitlinkit/fieldtypes/FruitLinkItFieldType.php(136): Craft\TemplatesService->render('fruitlinkit/_fi...', Array)
#18 /storage/av04327/www/craft/app/vendor/twig/twig/lib/Twig/Template.php(615): Craft\FruitLinkItFieldType->getInputHtml('buttonLink', '')
```

**Comment by edolyne** [comment]
It looks like this issue is only arising when a LinkIt field is within a matrix, when the field is outside of a matrix field everything functions appropriately.

**Comment by lukepearce** [comment]
Also receiving the same error.

I had just enabled a custom element type to be selectable.

Running Craft 2.6.3002 and Linkit 2.3.4

**Comment by kotyy** [comment]
I ran into this issue as well. In my case, it was caused because I had failed to select any Link Types for the field. It was also inside a matrix, but I did not test it outside of a matrix.
